source 'https://rubygems.org'
gem 'sinatra'
gem 'sqlite3'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sinatra-cross_origin', '~> 0.2.0'
gem 'oj', '~> 2.2.1'
gem 'nokogiri'


group :development do
  gem 'shotgun'
  gem 'tux'
end